# Generated by Django 5.0.2 on 2024-02-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=30)),
                ('breed', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
