# Generated by Django 5.0.2 on 2024-02-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pimage',
            field=models.ImageField(default=0, upload_to='image'),
        ),
    ]
